### ISSUE TITLE
split icons into its own package

### ISSUE THREAD

**Issue by MAHcodes** [lustre-labs/ui#12]
splitting icons into it's own separated package will enable websites and/or other libraries to utilize the icons independently, without being tied to lustre-ui, and will also enable us to incorporate additional icon sets beyond those from Radix

**Comment by hayleigh-dot-dev** [comment]
A number of good icon packages now exist to fill this gap. Instead of splitting icons into a separate package lustre/ui will just vendor a handful of icons it needs and leave icon choice down to the user in general.
