### ISSUE TITLE
Allow `gleam_json` v2.0

### ISSUE THREAD

**Issue by GearsDatapacks** [lustre-labs/ui#17]
I'm currently stuck using `lustre_ui` v0.4.0, because v0.6.0 constrains `gleam_json` to `~1`. Since `lustre` now allows `gleam_json@2`, it would be nice to allow it for `lustre_ui` as well

**Comment by cauebs** [comment]
Branch `v1` already uses `gleam_json>=2.0.0` so I assume this change has already been accepted by the author and it's just a matter of time until it makes its way to the main branch.

**Comment by hayleigh-dot-dev** [comment]
Aye, the v0 release is unmaintained at this point. I'll be releasing v1 fairly soon :)

**Comment by GearsDatapacks** [comment]
Ok then. Thanks!
